### ISSUE TITLE
模板文件不存在:./application/index/view/index/index.html

### ISSUE THREAD

**Issue by ggoog** [fungjcode/phpzhibo#1]
rt
<img width="1312" alt="image" src="https://user-images.githubusercontent.com/25149246/63746955-8ae0f300-c8d8-11e9-98c0-71b5846d096c.png">

**Comment by fungjcode** [comment]
粗心了，由于是在WIN系统下做的，所有没太注意大小写区分的问题

把文件夹/view/index/，大写I改成小写i就可以了

**Comment by ggoog** [comment]
已解决，多谢大佬分享
